apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: "beers-api-db"
objects:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: mongo
      app.kubernetes.io/component: mongo
      app.kubernetes.io/instance: mongo
      app.kubernetes.io/part-of: mongo
      app.openshift.io/runtime-version: latest
    name: mongo
  spec:
    ports:
    - name: 27017-tcp
      port: 27017
      protocol: TCP
      targetPort: 27017
    selector:
      app: mongo
      deploymentconfig: mongo
    sessionAffinity: None
    type: ClusterIP
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: mongo
      app.kubernetes.io/component: mongo
      app.kubernetes.io/instance: mongo
      app.kubernetes.io/part-of: mongo
      app.openshift.io/runtime: mongodb
    name: mongo
  spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      app: mongo
      deploymentconfig: mongo
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          app: mongo
          deploymentconfig: mongo
      spec:
        containers:
        - image: docker.io/library/mongo
          imagePullPolicy: IfNotPresent
          name: mongo
          ports:
          - containerPort: 27017
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /data/configdb
            name: mongo-1
          - mountPath: /data/db
            name: mongo-2
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - emptyDir: {}
          name: mongo-1
        - emptyDir: {}
          name: mongo-2
    test: false
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - mongo
        from:
          kind: ImageStreamTag
          name: mongo:latest
      type: ImageChange
    - type: ConfigChange
